export const SpecialGroup = [
    '残疾人',
    '低保',
    '低收入',
    '特困',
    '独生子女家庭',
    '计划生育特殊家庭',
    '单独家庭',
    '双独家庭',
    '失独家庭',
    '残疾人家庭',
    '空巢老人',
    '享受廉租住房补贴',
    '享受廉租住房',
    '享受公租房租房',
    '高龄补贴',
    '困难儿童',
    '留守儿童',
    '孤儿',
    '收养情况',
    '事实无人抚养',
    '精神疾病'
];

export const Nationality = [
    '汉族',
    '壮族',
    '满族',
    '回族',
    '苗族',
    '维吾尔族',
    '土家族',
    '彝族',
    '蒙古族',
    '藏族',
    '布依族',
    '侗族',
    '瑶族',
    '朝鲜族',
    '白族',
    '哈尼族',
    '哈萨克族',
    '黎族',
    '傣族',
    '畲族',
    '傈僳族',
    '仡佬族',
    '东乡族',
    '高山族',
    '拉祜族',
    '水族',
    '佤族',
    '纳西族',
    '羌族',
    '土族',
    '仫佬族',
    '锡伯族',
    '柯尔克孜族',
    '达斡尔族',
    '景颇族',
    '毛南族',
    '撒拉族',
    '布朗族',
    '塔吉克族',
    '阿昌族',
    '普米族',
    '鄂温克族',
    '怒族',
    '京族',
    '基诺族',
    '德昂族',
    '保安族',
    '俄罗斯族',
    '裕固族',
    '乌兹别克族',
    '门巴族',
    '鄂伦春族',
    '独龙族',
    '塔塔尔族',
    '赫哲族',
    '珞巴族'
];


export const Education = [
    '小学',
    '初中',
    '高中',
    '大专',
    '本科',
    '硕士',
    '博士'
];

export const relation =
    [
        { index: '02', relation: '户主' },
        { index: '03', relation: '小集体户主' },
        { index: '10', relation: '配偶' },
        { index: '11', relation: '夫' },
        { index: '12', relation: '妻' },
        { index: '20', relation: '子' },
        { index: '21', relation: '独生子' },
        { index: '22', relation: '长子' },
        { index: '23', relation: '次子' },
        { index: '24', relation: '三子' },
        { index: '25', relation: '四子' },
        { index: '26', relation: '五子' },
        { index: '27', relation: '养子或继子' },
        { index: '28', relation: '女婿' },
        { index: '29', relation: '其它儿子' },
        { index: '30', relation: '女' },
        { index: '31', relation: '独生女' },
        { index: '32', relation: '长女' },
        { index: '33', relation: '二女' },
        { index: '34', relation: '三女' },
        { index: '35', relation: '四女' },
        { index: '36', relation: '五女' },
        { index: '37', relation: '养女或继女' },
        { index: '38', relation: '儿媳' },
        { index: '39', relation: '其它女儿' },
        { index: '40', relation: '孙子,孙女或外孙子,外孙女' },
        { index: '41', relation: '孙子' },
        { index: '42', relation: '孙女' },
        { index: '43', relation: '外孙子' },
        { index: '44', relation: '外孙女' },
        { index: '45', relation: '孙媳妇或外孙媳妇' },
        { index: '46', relation: '孙女婿或外孙女婿' },
        { index: '47', relation: '曾孙子或曾外孙子' },
        { index: '48', relation: '曾孙女或曾外孙女' },
        { index: '49', relation: '其他孙子、孙女或外孙子、外孙女' },
        { index: '50', relation: '父母' },
        { index: '51', relation: '父亲' },
        { index: '52', relation: '母亲' },
        { index: '53', relation: '公公' },
        { index: '54', relation: '婆婆' },
        { index: '55', relation: '岳父' },
        { index: '56', relation: '岳母' },
        { index: '57', relation: '继父或养父' },
        { index: '58', relation: '继母或养母' },
        { index: '59', relation: '其它父母关系' },
        { index: '60', relation: '祖父母或外祖父母' },
        { index: '61', relation: '祖父' },
        { index: '62', relation: '祖母' },
        { index: '63', relation: '外祖父' },
        { index: '64', relation: '外祖母' },
        { index: '65', relation: '配偶的祖父母或外祖父母' },
        { index: '66', relation: '曾祖父' },
        { index: '67', relation: '曾祖母' },
        { index: '68', relation: '配偶的曾祖父母' },
        { index: '69', relation: '其它祖父母或外祖父母关系' },
        { index: '70', relation: '兄弟姐妹' },
        { index: '71', relation: '兄' },
        { index: '72', relation: '嫂' },
        { index: '73', relation: '弟' },
        { index: '74', relation: '弟媳' },
        { index: '75', relation: '姐姐' },
        { index: '76', relation: '姐夫' },
        { index: '77', relation: '妹妹' },
        { index: '78', relation: '妹夫' },
        { index: '79', relation: '其它兄弟姐妹' },
        { index: '80', relation: '其它' },
        { index: '81', relation: '伯父' },
        { index: '82', relation: '伯母' },
        { index: '83', relation: '叔父' },
        { index: '84', relation: '婶母' },
        { index: '85', relation: '舅父' },
        { index: '86', relation: '舅母' },
        { index: '87', relation: '姨父' },
        { index: '88', relation: '姨母' },
        { index: '89', relation: '姑父' },
        { index: '90', relation: '姑母' },
        { index: '91', relation: '堂兄弟、堂姐妹' },
        { index: '92', relation: '表兄弟、表姐妹' },
        { index: '93', relation: '侄子' },
        { index: '94', relation: '侄女' },
        { index: '95', relation: '外甥' },
        { index: '96', relation: '外甥女' },
        { index: '97', relation: '其他亲属' },
        { index: '98', relation: '保姆' },
        { index: '99', relation: '非亲属' }
    ];
