export const SpecialGroup = [
  '残疾人',
  '低保',
  '低收入',
  '特困',
  '独生子女家庭',
  '计划生育特殊家庭',
  '单独家庭',
  '双独家庭',
  '失独家庭',
  '残疾人家庭',
  '空巢老人',
  '享受廉租住房补贴',
  '享受廉租住房',
  '享受公租房租房',
  '高龄补贴',
  '困难儿童',
  '留守儿童',
  '孤儿',
  '收养情况',
  '事实无人抚养',
  '精神疾病',
];

export const Nationality = [
  '汉族',
  '壮族',
  '满族',
  '回族',
  '苗族',
  '维吾尔族',
  '土家族',
  '彝族',
  '蒙古族',
  '藏族',
  '布依族',
  '侗族',
  '瑶族',
  '朝鲜族',
  '白族',
  '哈尼族',
  '哈萨克族',
  '黎族',
  '傣族',
  '畲族',
  '傈僳族',
  '仡佬族',
  '东乡族',
  '高山族',
  '拉祜族',
  '水族',
  '佤族',
  '纳西族',
  '羌族',
  '土族',
  '仫佬族',
  '锡伯族',
  '柯尔克孜族',
  '达斡尔族',
  '景颇族',
  '毛南族',
  '撒拉族',
  '布朗族',
  '塔吉克族',
  '阿昌族',
  '普米族',
  '鄂温克族',
  '怒族',
  '京族',
  '基诺族',
  '德昂族',
  '保安族',
  '俄罗斯族',
  '裕固族',
  '乌兹别克族',
  '门巴族',
  '鄂伦春族',
  '独龙族',
  '塔塔尔族',
  '赫哲族',
  '珞巴族',
];

export const Education = ['小学', '初中', '高中', '大专', '本科', '硕士', '博士'];

export const relation = [
  { index: '02', relation: '父子' },
  { index: '03', relation: '父女' },
  { index: '10', relation: '母子' },
  { index: '11', relation: '母女' },
  { index: '12', relation: '夫妻' },
  { index: '20', relation: '兄弟' },
  { index: '21', relation: '姐弟' },
  { index: '22', relation: '兄妹' },
  { index: '23', relation: '姐妹' },
  { index: '24', relation: '爷爷-孙子' },
  { index: '25', relation: '爷爷-孙女' },
  { index: '26', relation: '奶奶-孙女' },
  { index: '27', relation: '奶奶-孙子' },
  { index: '28', relation: '姥姥-孙子' },
  { index: '29', relation: '姥姥-孙女' },
  { index: '30', relation: '姥爷-孙女' },
  { index: '31', relation: '姥爷-孙子' },
  { index: '32', relation: '儿媳' },
  { index: '33', relation: '女婿' },
  { index: '36', relation: '养父-养子' },
  { index: '37', relation: '养母-养女' },
  { index: '38', relation: '养父-养女' },
  { index: '39', relation: '养父-养子' },
  { index: '40', relation: '伯父-侄子' },
  { index: '41', relation: '伯母-侄子' },
  { index: '42', relation: '叔父-侄子' },
  { index: '43', relation: '婶母-侄子' },
  { index: '44', relation: '舅父-侄子' },
  { index: '45', relation: '舅母-侄子' },
  { index: '46', relation: '姨父-侄子' },
  { index: '47', relation: '姨母-侄子' },
  { index: '48', relation: '姑父-侄子' },
  { index: '49', relation: '姑母-侄子' },
  { index: '50', relation: '伯父-侄女' },
  { index: '51', relation: '伯母-侄女' },
  { index: '52', relation: '叔父-侄女' },
  { index: '53', relation: '婶母-侄女' },
  { index: '54', relation: '舅父-侄女' },
  { index: '55', relation: '舅母-侄女' },
  { index: '56', relation: '姨父-侄女' },
  { index: '57', relation: '姨母-侄女' },
  { index: '58', relation: '姑父-侄女' },
  { index: '59', relation: '姑母-侄女' },
  { index: '71', relation: '伯父-侄女' },
  { index: '72', relation: '伯母-外女' },
  { index: '73', relation: '叔父-外女' },
  { index: '74', relation: '婶母-外女' },
  { index: '75', relation: '舅父-外女' },
  { index: '76', relation: '舅母-外女' },
  { index: '77', relation: '姨父-外女' },
  { index: '78', relation: '姨母-外女' },
  { index: '79', relation: '姑父-外女' },
  { index: '70', relation: '姑母-外女' },
  { index: '81', relation: '伯父-外甥' },
  { index: '82', relation: '伯母-外甥' },
  { index: '83', relation: '叔父-外甥' },
  { index: '84', relation: '婶母-外甥' },
  { index: '85', relation: '舅父-外甥' },
  { index: '86', relation: '舅母-外甥' },
  { index: '87', relation: '姨父-外甥' },
  { index: '88', relation: '姨母-外甥' },
  { index: '89', relation: '姑父-外甥' },
  { index: '90', relation: '姑母-外甥' },
  { index: '91', relation: '堂兄弟' },
  { index: '92', relation: '表兄弟' },
  { index: '95', relation: '堂姐妹' },
  { index: '96', relation: '表姐妹' },
  { index: '97', relation: '其他亲属' },
  { index: '98', relation: '保姆' },
  { index: '99', relation: '非亲属' },
];
