name: 自动构建/自动部署部署流程

on:
  push:
    branches:
      - newdev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: 安装依赖
        run: yarn install

      - name: 代码格式检查
        run: yarn run lint

      - name: 类型检查
        run: yarn run type-check

      - name: 构建
        run: yarn run build:prod

      - name: 打包构建工件
        run: |
          mkdir artifact
          mv dist artifact/
        shell: bash

      - name: 上传构建工件
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact/

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 下载构建工件
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /opt/mohe/front/dist/
          remote_host: ${{ secrets.DEPLOY_HOST_DEV }}
          remote_user: ${{ secrets.DEPLOY_USER_DEV }}
          remote_key: ${{ secrets.DEPLOY_KEY_DEV }}
