name: CI/CD

on:
  push:
    branches:
      - newdev
  pull_request:
    branches:
      - newdev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.1

      - name: 安装依赖
        run: npm ci

      - name: 代码格式检查
        run: npm run lint

      - name: 类型检查
        run: npm run type-check

      - name: 构建
        run: npm run build:prod

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装 SSH 私钥
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: 构建部署
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/opt/mohe/front-end-mohe/
