name: CI/CD

on:
  push:
    branches:
      - newdev
  pull_request:
    branches:
      - newdev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 获取代码
        uses: actions/checkout@v2

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.1

      - name: 安装依赖
        run: npm ci

      - name: 代码质量检查
        run: npm run lint

      - name: 类型检查
        run: npm run type-check

      - name: 构建项目
        run: npm run build:prod

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: rsync -avz --delete ./dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/mohe/front-end-mohe/
